In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [62]:
lr = LogisticRegression(solver='newton-cg')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9722222222222222

In [63]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9861111111111112

In [64]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9694444444444444

In [65]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [66]:
for train_index, test_index in kf.split([i for i in range(1,10)]):
    print(train_index, test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [67]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [68]:
get_score(LogisticRegression(solver='newton-cg'), X_train, X_test, y_train, y_test)

0.9722222222222222

In [69]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9694444444444444

In [70]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9861111111111112

In [71]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [80]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='newton-cg'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

print(scores_l)
print(scores_svm)
print(scores_rf)


[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]
[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
[0.9248747913188647, 0.9499165275459098, 0.9298831385642737]


In [81]:
from sklearn.model_selection import cross_val_score

In [85]:
cross_val_score(LogisticRegression(solver='newton-cg'), digits.data, digits.target)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [87]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [89]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.92777778, 0.9       , 0.94428969, 0.95821727, 0.92200557])

In [90]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target)

array([0.92777778, 0.91944444, 0.95543175, 0.9637883 , 0.92200557])